language: python
python:
    - "2.7"

install:
    - pip install clustershell
    - pip install coverage
    - pip install codecov

# Shine needs same names for getfqdn() and hostname()
addons:
  hostname: shine-hostname.shine-domain.net
  hosts:
     - shine-hostname
     - shine-hostname.shine-domain.net

before_script:
    # Allow us to SSH passwordless to local host
    - ssh-keygen -f ~/.ssh/id_rsa -N ""
    - cp ~/.ssh/{id_rsa.pub,authorized_keys}
    # Avoid ssh "known hosts" warnings
    - printf '%s\n    %s\n    %s\n' 'Host *' 'StrictHostKeyChecking no' 'LogLevel ERROR' >> ~/.ssh/config

script:
    - cd tests; PYTHONPATH=$PYTHONPATH:$PWD/../lib nosetests -v --all-modules --with-coverage

# Push the results back to codecov
after_success:
    - codecov
