language: python
python:
    - "2.6"
    - "2.7"

install:
    - pip install clustershell
    - pip install coverage
    - pip install codecov

before_script:
    # Allow us to SSH passwordless to local host
    - ssh-keygen -f ~/.ssh/id_rsa -N ""
    - cp ~/.ssh/{id_rsa.pub,authorized_keys}
    # Avoid ssh "known hosts" warnings
    - printf '%s\n    %s\n    %s\n' 'Host *' 'StrictHostKeyChecking no' 'LogLevel ERROR' >> ~/.ssh/config

script:
    - echo -e "[general]\nnoformat_dev=/dev/sda\nnoformat_jdev=/dev/sda1\n" > tests/tests.conf
    - cd tests; PYTHONPATH=$PYTHONPATH:$PWD/../lib nosetests -v --all-modules --with-coverage -I CmdTest.py

# Push the results back to codecov
after_success:
    - codecov
