#!/usr/bin/env python
# Copyright (C) 2007, 2008, 2009 CEA
#
# This file is part of shine
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
# $Id$

"""
Lustre 1.6+ filesystem administration tool.
"""

__version__ = "$Revision$"
__author__ = "Stephane Thiell"


import getopt
import sys

sys.path.append("../lib")

from Shine import public_version, __version__ as __libversion__
from Shine.Controller import Controller


def usage(controller):
    print """Usage: shine <command> [options...]
"""
    controller.usage()

def main():
    
    controller = Controller()

    if len(sys.argv) < 2 or sys.argv[1] in ["help", '-h', '--help']:
        usage(controller)
        sys.exit(2)

    if sys.argv[1] in ["version", "-v", "--version"]:
        print "%s lib %s script %s" % (public_version, __libversion__, __version__)
        sys.exit(0)

    try:
        rc = controller.run_command(sys.argv[1:])
        sys.exit(rc)
    except KeyError:
        usage(controller)
        sys.exit(2)
    except (KeyboardInterrupt, SystemExit):
        print >>sys.stderr, "Exiting."
        sys.exit(2)
        

if __name__ == '__main__':
    main()
